import { requireAdmin,requireSession } from '../../../../lib/auth';
import { query } from '../../../../lib/db';
import { editorContext } from '../../../../lib/members';
import { queueNotification,deliverNotification } from '../../../../lib/notifications';
import { put,get,remove } from '../../../../lib/storage';
import { randomUUID } from 'node:crypto';
export const dynamic='force-dynamic';
const types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
async function requirePhotoEditor(id){try{return {user:await requireAdmin(),admin:true}}catch(error){if(error.status!==401&&error.status!==403)throw error;const user=await requireSession(),access=await editorContext(user.id,id);return {user,admin:false,access};}}
async function memberPhotoNotice(editor,id,action){if(editor.admin)return true;const p=await query('select name_he from people where id=$1',[id]);await query("insert into profile_audit_log(target_person_id,actor_user_id,actor_person_id,action,changes) values($1,$2,$3,$4,'{}'::jsonb)",[id,editor.user.id,editor.access.actorPersonId,action]);const notificationId=await queueNotification({query},{recipient:process.env.ADMIN_NOTIFICATION_EMAIL||'ilayspo@gmail.com',subject:`עדכון תמונה בפרופיל: ${p.rows[0]?.name_he||id}`,lines:[action==='photo_updated'?'הועלתה או הוחלפה תמונת הפרופיל.':'תמונת הפרופיל הוסרה.',editor.access.access==='self'?'הפעולה בוצעה על ידי בעל/ת הפרופיל.':'הפעולה בוצעה על ידי הורה שקיבל הרשאה.']});return (await deliverNotification(notificationId)).sent;}
const sameOrigin=req=>{const origin=req.headers.get('origin');return !origin||new URL(origin).host===new URL(req.url).host;};
export async function GET(req,{params}){try{const {id}=await params;const r=await query('select photo_key,is_visible from people where id=$1',[id]);if(!r.rowCount||!r.rows[0].is_visible||!r.rows[0].photo_key)return new Response(null,{status:404});const file=await get(r.rows[0].photo_key);return new Response(file.Body.transformToWebStream(),{headers:{'Content-Type':file.ContentType||'image/jpeg','Cache-Control':'no-store'}});}catch(e){console.error(e);return new Response(null,{status:503});}}
export async function PUT(req,{params}){let key;try{if(!sameOrigin(req))throw Object.assign(new Error('בקשה ממקור לא מורשה.'),{status:403});const {id}=await params,editor=await requirePhotoEditor(id);const file=(await req.formData()).get('file');if(!file||!types[file.type]||file.size>5*1024*1024||file.size===0)return Response.json({error:'בחרו קובץ JPG, PNG או WebP עד 5MB.'},{status:400});const bytes=Buffer.from(await file.arrayBuffer());const sig=bytes.subarray(0,12).toString('hex');const valid=file.type==='image/jpeg'?sig.startsWith('ffd8ff'):file.type==='image/png'?sig.startsWith('89504e470d0a1a0a'):sig.startsWith('52494646')&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)return Response.json({error:'סוג הקובץ אינו תואם לתמונה.'},{status:400});const old=await query('select photo_key from people where id=$1',[id]);if(!old.rowCount)return new Response(null,{status:404});key=`people/${id}/${randomUUID()}.${types[file.type]}`;await put(key,bytes,file.type);await query('update people set photo_key=$2,updated_at=now() where id=$1',[id,key]);if(old.rows[0].photo_key)try{await remove(old.rows[0].photo_key)}catch(e){console.error('Old photo cleanup failed',e)}const emailSent=await memberPhotoNotice(editor,id,'photo_updated');return Response.json({ok:true,emailSent});}catch(e){if(key)try{await remove(key)}catch{}console.error(e);return Response.json({error:e.status?e.message:'העלאת התמונה נכשלה.'},{status:e.status||500});}}
export async function DELETE(req,{params}){try{if(!sameOrigin(req))throw Object.assign(new Error('בקשה ממקור לא מורשה.'),{status:403});const {id}=await params,editor=await requirePhotoEditor(id);const old=await query('select photo_key from people where id=$1',[id]);if(!old.rowCount)return new Response(null,{status:404});await query('update people set photo_key=null,updated_at=now() where id=$1',[id]);if(old.rows[0].photo_key)await remove(old.rows[0].photo_key);const emailSent=await memberPhotoNotice(editor,id,'photo_removed');return Response.json({ok:true,emailSent});}catch(e){console.error(e);return Response.json({error:e.status?e.message:'הסרת התמונה נכשלה.'},{status:e.status||500});}}
