import { requireAdmin } from '../../../../lib/auth';
import { query } from '../../../../lib/db';
import { put,get,remove } from '../../../../lib/storage';
import { randomUUID } from 'node:crypto';
export const dynamic='force-dynamic';
const types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
export async function GET(req,{params}){try{const {id}=await params;const r=await query('select photo_key,is_visible from people where id=$1',[id]);if(!r.rowCount||!r.rows[0].is_visible||!r.rows[0].photo_key)return new Response(null,{status:404});const file=await get(r.rows[0].photo_key);return new Response(file.Body.transformToWebStream(),{headers:{'Content-Type':file.ContentType||'image/jpeg','Cache-Control':'no-store'}});}catch(e){console.error(e);return new Response(null,{status:503});}}
export async function PUT(req,{params}){let key;try{await requireAdmin();const {id}=await params;const file=(await req.formData()).get('file');if(!file||!types[file.type]||file.size>5*1024*1024||file.size===0)return Response.json({error:'בחרו קובץ JPG, PNG או WebP עד 5MB.'},{status:400});const bytes=Buffer.from(await file.arrayBuffer());const sig=bytes.subarray(0,12).toString('hex');const valid=file.type==='image/jpeg'?sig.startsWith('ffd8ff'):file.type==='image/png'?sig.startsWith('89504e470d0a1a0a'):sig.startsWith('52494646')&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)return Response.json({error:'סוג הקובץ אינו תואם לתמונה.'},{status:400});const old=await query('select photo_key from people where id=$1',[id]);if(!old.rowCount)return new Response(null,{status:404});key=`people/${id}/${randomUUID()}.${types[file.type]}`;await put(key,bytes,file.type);await query('update people set photo_key=$2,updated_at=now() where id=$1',[id,key]);if(old.rows[0].photo_key)try{await remove(old.rows[0].photo_key)}catch(e){console.error('Old photo cleanup failed',e)}return Response.json({ok:true});}catch(e){if(key)try{await remove(key)}catch{}console.error(e);return Response.json({error:e.status?e.message:'העלאת התמונה נכשלה.'},{status:e.status||500});}}
export async function DELETE(req,{params}){try{await requireAdmin();const {id}=await params;const old=await query('select photo_key from people where id=$1',[id]);if(!old.rowCount)return new Response(null,{status:404});await query('update people set photo_key=null,updated_at=now() where id=$1',[id]);if(old.rows[0].photo_key)await remove(old.rows[0].photo_key);return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:e.status?e.message:'הסרת התמונה נכשלה.'},{status:e.status||500});}}
